{
  "closed_by": {
    "organizations_url": "https://api.github.com/users/zoffixznet/orgs",
    "avatar_url": "https://avatars2.githubusercontent.com/u/5747918?v=4",
    "id": 5747918,
    "site_admin": false,
    "type": "User",
    "received_events_url": "https://api.github.com/users/zoffixznet/received_events",
    "subscriptions_url": "https://api.github.com/users/zoffixznet/subscriptions",
    "starred_url": "https://api.github.com/users/zoffixznet/starred{/owner}{/repo}",
    "html_url": "https://github.com/zoffixznet",
    "url": "https://api.github.com/users/zoffixznet",
    "node_id": "MDQ6VXNlcjU3NDc5MTg=",
    "gravatar_id": "",
    "gists_url": "https://api.github.com/users/zoffixznet/gists{/gist_id}",
    "following_url": "https://api.github.com/users/zoffixznet/following{/other_user}",
    "followers_url": "https://api.github.com/users/zoffixznet/followers",
    "events_url": "https://api.github.com/users/zoffixznet/events{/privacy}",
    "repos_url": "https://api.github.com/users/zoffixznet/repos",
    "login": "zoffixznet"
  },
  "closed_at": "2016-08-17T18:18:17Z",
  "title": "Docs for await in Promise should include a way to watch for broken promises",
  "id": 118379794,
  "created_at": "2015-11-23T13:26:22Z",
  "user": {
    "organizations_url": "https://api.github.com/users/zoffixznet/orgs",
    "avatar_url": "https://avatars2.githubusercontent.com/u/5747918?v=4",
    "id": 5747918,
    "site_admin": false,
    "type": "User",
    "received_events_url": "https://api.github.com/users/zoffixznet/received_events",
    "subscriptions_url": "https://api.github.com/users/zoffixznet/subscriptions",
    "starred_url": "https://api.github.com/users/zoffixznet/starred{/owner}{/repo}",
    "html_url": "https://github.com/zoffixznet",
    "url": "https://api.github.com/users/zoffixznet",
    "node_id": "MDQ6VXNlcjU3NDc5MTg=",
    "gravatar_id": "",
    "gists_url": "https://api.github.com/users/zoffixznet/gists{/gist_id}",
    "following_url": "https://api.github.com/users/zoffixznet/following{/other_user}",
    "followers_url": "https://api.github.com/users/zoffixznet/followers",
    "events_url": "https://api.github.com/users/zoffixznet/events{/privacy}",
    "repos_url": "https://api.github.com/users/zoffixznet/repos",
    "login": "zoffixznet"
  },
  "locked": false,
  "node_id": "MDU6SXNzdWUxMTgzNzk3OTQ=",
  "html_url": "https://github.com/perl6/doc/issues/208",
  "url": "https://api.github.com/repos/perl6/doc/issues/208",
  "labels": [
    {
      "id": 244843225,
      "name": "docs",
      "url": "https://api.github.com/repos/perl6/doc/labels/docs",
      "node_id": "MDU6TGFiZWwyNDQ4NDMyMjU=",
      "default": false,
      "color": "5DE0FA"
    }
  ],
  "labels_url": "https://api.github.com/repos/perl6/doc/issues/208/labels{/name}",
  "author_association": "MEMBER",
  "assignee": null,
  "state": "closed",
  "comments_url": "https://api.github.com/repos/perl6/doc/issues/208/comments",
  "body": "Since `await $p1, $p2` will throw if any of the Promises were broken, we should show an example of how to check for broken promises and fetch the results for kept promises, even if some were broken.\n\nIt seems the idiomatic way is to use `await Promise.allof( $p1, $p2 )`, but currently that will throw if any of the promises is broken. jnthn++ believes that's a bug. See this conversation: http://irclog.perlgeek.de/perl6/2015-11-23#i_11585114\n\nOnce the bug  is resolved, the docs should be updated to include correct handling of broken promises, something akin to this, except with `Promise.allof()` instead of `eager`:\n\n``` perl6\nmy $p1 = start die \"I'm dead\";\nmy $p2 = start \"I'm alive\";\ntry eager await $p1, $p2;\nsay .result for grep { .status ~~ 'Kept'}, $p1, $p2;\n```\n",
  "assignees": [
    
  ],
  "updated_at": "2016-08-17T18:18:17Z",
  "comments": 2,
  "milestone": null,
  "number": 208,
  "events_url": "https://api.github.com/repos/perl6/doc/issues/208/events",
  "repository_url": "https://api.github.com/repos/perl6/doc"
}